"""creación inicial de tablas

Revision ID: 26ac2f417cf6
Revises: 
Create Date: 2026-06-21 12:44:38.198394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ac2f417cf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilitador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facilitador_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('umbral_aprobacion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facilitador_id'], ['facilitador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('abierta_at', sa.DateTime(), nullable=False),
    sa.Column('cerrada_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('alternativa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('identificador_hash', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('ingreso_at', sa.DateTime(), nullable=False),
    sa.Column('finalizado_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sesion_id', 'identificador_hash', name='uq_participante_sesion_hash')
    )
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.create_index('ix_participante_identificador_hash', ['identificador_hash'], unique=False)

    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('alternativa_id', sa.Integer(), nullable=False),
    sa.Column('enviada_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alternativa_id'], ['alternativa.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participante.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id', 'pregunta_id', name='uq_respuesta_participante_pregunta')
    )
    op.create_table('resultado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('calculado_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado')
    op.drop_table('respuesta')
    with op.batch_alter_table('participante', schema=None) as batch_op:
        batch_op.drop_index('ix_participante_identificador_hash')

    op.drop_table('participante')
    op.drop_table('alternativa')
    op.drop_table('sesion')
    op.drop_table('pregunta')
    op.drop_table('evaluacion')
    op.drop_table('facilitador')
    # ### end Alembic commands ###
